# Generated by Django 4.1 on 2022-08-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_teammembers_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
