# Generated by Django 4.1 on 2022-08-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_task_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
